# Generated by Django 4.1.4 on 2022-12-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_news_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.PositiveIntegerField()),
            ],
        ),
    ]
