# Generated by Django 4.1.4 on 2022-12-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_newid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='id_new',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newid',
            name='new_id',
            field=models.CharField(max_length=255),
        ),
    ]
