# Generated by Django 4.1.4 on 2022-12-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_new_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='summery',
            new_name='summary',
        ),
    ]
